libticables: add cmake check for parallel and serial includes
debrouxl/tilibs pull request #60
Opened 2022-01-30 23:27 UTC by davide125

Check for the includes for parallel and serial support and set the relevant defines, so that support can be compiled in when available.

2022-01-31 06:46 UTC, debrouxl commented
The changes look sound.
@adriweb ?

2022-01-31 08:30 UTC, adriweb commented
Looks good to me but I'll check on macOS quickly.

2022-01-31 11:05 UTC, adriweb commented
Well, it fails to build now for me:

```
[ 96%] Linking CXX shared library libticables2.dylib
undef: _cable_par
Undefined symbols for architecture x86_64:
  "_cable_par
 ```

We can see the usage here in ticables.cc:

```c
#if !defined(NO_CABLE_PAR) && (defined(HAVE_LINUX_PARPORT_H) || defined(__WIN32__))
	&cable_par,
#endif
```

Looking at the changes a bit more, it's because defining a macro with no value still makes it defined, so the check in the code ends up not doing what we want.

So, if we don't want to change the code (to check for an actual value, like `1` which cmake uses, not sure about the autotools), only the CMakeLists.txt, we should do that:
```
if (HAVE_LINUX_PARPORT_H)
    target_compile_definitions(ticables2_objlib PUBLIC HAVE_LINUX_PARPORT_H=1)
endif()
if (HAVE_LINUX_SERIAL_H)
    target_compile_definitions(ticables2_objlib PUBLIC HAVE_LINUX_SERIAL_H=1)
endif()
```

2022-01-31 11:06 UTC, adriweb requested changes

2022-01-31 11:06 UTC, adriweb commented on libticables/trunk/CMakeLists.txt
> +target_compile_definitions(ticables2_objlib PUBLIC HAVE_LIBUSB_1_0=1 HAVE_LIBUSB10_STRERROR=1 HAVE_TERMIOS_H=1 HAVE_LINUX_PARPORT_H=${HAVE_LINUX_PARPORT_H} HAVE_LINUX_SERIAL_H=${HAVE_LINUX_SERIAL_H})
```suggestion
target_compile_definitions(ticables2_objlib PUBLIC HAVE_LIBUSB_1_0=1 HAVE_LIBUSB10_STRERROR=1 HAVE_TERMIOS_H=1)

# check includes for parallel and serial support
include(CheckIncludeFile)
CHECK_INCLUDE_FILE(linux/parport.h HAVE_LINUX_PARPORT_H)
CHECK_INCLUDE_FILE(linux/serial.h HAVE_LINUX_SERIAL_H)
if (HAVE_LINUX_PARPORT_H)
    target_compile_definitions(ticables2_objlib PUBLIC HAVE_LINUX_PARPORT_H=1)
endif()
if (HAVE_LINUX_SERIAL_H)
    target_compile_definitions(ticables2_objlib PUBLIC HAVE_LINUX_SERIAL_H=1)
endif()
```

2022-01-31 16:11 UTC, adriweb approved these changes

2022-01-31 16:14 UTC, davide125 commented
Thanks! I forgot cmake doesn't like undefined variables. I've retested on my end and confirmed this still does the right thing on Linux.

2022-01-31 16:15 UTC, adriweb commented
No problem, I'm not a CMake expert anyway, so I wouldn't have caught it if I hadn't tried :P

2022-02-01 08:18 UTC, merged

2022-02-01 08:23 UTC, debrouxl commented
Thanks :)